name: CI

on: 
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      env:
        DOCKER_HUB: ${{ secrets.DOCKERHUB }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKERHUB_KEY }}
      run: |
        ls -l
        echo 'Docker login'
        docker login -u $DOCKERHUB -p $DOCKERHUB_KEY
        echo 'Running build...'
        docker build . -t shashidhar/entityservice:latest
        echo 'Pushing image...'
        docker push shashidhar/entityservice:latest
        echo 'Done!'
